"""
claude_composition.py — NOT generated by an algorithm and not pulled from
a model. This is me (Claude) composing directly: every note, chord, and
rest below is a deliberate choice, written the same way I'd write any
other creative content in this conversation. That's the workflow you
pointed at being "easier than Suno" — no prompt describing a vibe for a
black box to interpret, this is the actual score, in the open, editable
by hand.

Key: D minor. Progression: i - VI - III - VII (Dm - Bb - F - C) — the
loop this whole genre leans on. 4 bars / 16th-note grid, 174 BPM.
distorted_lead stays silent in bar 1 (let the groove sit alone first),
asks a rising question in bar 2, answers lower in bar 3, then climbs to
the piece's highest note in bar 4 right before the loop resolves back to
Dm. Bass pushes from straight quarters into driving 8ths in bars 3-4 for
momentum into that peak. PSG arpeggiates the current chord (not a fixed
shape — it changes with the harmony) with a noise tick on the "and".
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "python"))

from events import (Wait, FMInstrumentSelect, FMNoteOn, FMNoteOff,
                     PSGToneOn, PSGToneOff, PSGNoiseOn, PSGNoiseOff, End)

BPM = 174
TICKS_PER_SECOND = 192.0


def _ticks(beats: float) -> int:
    return max(1, round(beats * 60.0 / BPM * TICKS_PER_SECOND))


CHORDS = [  # one per bar -> (channel 2, channel 3, channel 4)
    [("D", 3), ("F", 3), ("A", 3)],    # i    Dm
    [("A#", 2), ("D", 3), ("F", 3)],   # VI   Bb
    [("F", 2), ("A", 2), ("C", 3)],    # III  F
    [("C", 3), ("E", 3), ("G", 3)],    # VII  C
]

BASS_ROOT = [("D", 2), ("A#", 1), ("F", 1), ("C", 2)]

# (absolute 16th-note step 0-63, note, octave, length in steps)
LEAD_NOTES = [
    (18, "A", 3, 2), (20, "A#", 3, 2), (22, "C", 4, 2),
    (26, "D", 4, 2), (28, "C", 4, 2), (30, "A#", 3, 2),
    (33, "A", 2, 2), (35, "C", 3, 3), (38, "F", 3, 3),
    (41, "A", 3, 3), (44, "G", 3, 4),
    (48, "C", 3, 2), (50, "E", 3, 2), (52, "G", 3, 2), (54, "A", 3, 2),
    (56, "C", 4, 2), (59, "D", 4, 3), (62, "D", 4, 2),
]


def _arp_note(bar_idx: int, step_in_bar: int):
    root, third, fifth = CHORDS[bar_idx]
    cycle = [root, third, fifth, (third[0], third[1] + 1)]
    note, octv = cycle[step_in_bar % 4]
    return note, octv + 2  # lift into a bright PSG register above the FM chord


def compose():
    events = [
        FMInstrumentSelect(channel=0, instrument="bass"),
        FMInstrumentSelect(channel=1, instrument="distorted_lead"),
        FMInstrumentSelect(channel=2, instrument="jazz_chord_pad"),
        FMInstrumentSelect(channel=3, instrument="jazz_chord_pad"),
        FMInstrumentSelect(channel=4, instrument="jazz_chord_pad"),
    ]

    lead_starts = {s: (n, o, l) for s, n, o, l in LEAD_NOTES}
    bass_starts = {}
    for bar in range(4):
        note, octv = BASS_ROOT[bar]
        base = bar * 16
        bass_starts[base + 0] = (note, octv, 4)
        bass_starts[base + 4] = (note, octv, 4)
        bass_starts[base + 8] = (note, octv, 4)
        if bar >= 2:
            bass_starts[base + 12] = (note, octv, 2)
            bass_starts[base + 14] = (note, octv, 2)
        else:
            bass_starts[base + 12] = (note, octv, 4)

    bass_off_at = lead_off_at = None
    total_steps = 4 * 16

    for s in range(total_steps):
        if s % 16 == 0:
            bar = s // 16
            if s > 0:
                for ch in (2, 3, 4):
                    events.append(FMNoteOff(channel=ch))
            for ch, (note, octv) in zip((2, 3, 4), CHORDS[bar]):
                events.append(FMNoteOn(channel=ch, note=note, octave=octv))

        if bass_off_at == s:
            events.append(FMNoteOff(channel=0))
            bass_off_at = None
        if lead_off_at == s:
            events.append(FMNoteOff(channel=1))
            lead_off_at = None

        if s in bass_starts:
            note, octv, length = bass_starts[s]
            events.append(FMNoteOn(channel=0, note=note, octave=octv))
            bass_off_at = s + length

        if s in lead_starts:
            note, octv, length = lead_starts[s]
            events.append(FMNoteOn(channel=1, note=note, octave=octv))
            lead_off_at = s + length

        arp_note, arp_oct = _arp_note(s // 16, s % 16)
        events.append(PSGToneOn(channel=0, note=arp_note, octave=arp_oct, volume=4))
        if s % 4 == 2:
            events.append(PSGNoiseOn(white=True, rate=1, volume=8))

        events.append(Wait(ticks=_ticks(0.25)))

        events.append(PSGToneOff(channel=0))
        events.append(PSGNoiseOff())

    if bass_off_at is not None:
        events.append(FMNoteOff(channel=0))
    if lead_off_at is not None:
        events.append(FMNoteOff(channel=1))
    for ch in (2, 3, 4):
        events.append(FMNoteOff(channel=ch))

    events.append(End())
    return events


OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "output")


if __name__ == "__main__":
    import wavio
    import vgm
    from sequencer import Sequencer

    events = compose()
    print(f"{len(events)} events, {BPM} BPM, D minor, 4 bars")

    seq = Sequencer(ticks_per_second=TICKS_PER_SECOND)
    tag = vgm.GD3(title="chipgen: D minor loop", author="Claude",
                  notes="Composed by hand as an event list, not generated.")
    wav_path = os.path.join(OUTPUT_DIR, "claude_composition.wav")
    vgm_path = os.path.join(OUTPUT_DIR, "claude_composition.vgm")

    audio = seq.render_to_file(events, wav_path, vgm_path=vgm_path, gd3=tag)
    print(f"rendered {wavio.describe(audio, seq.target_rate)}")
    print(f"wrote {wav_path}")
    print(f"wrote {vgm_path}  (plays in any VGM player, imports into DefleMask)")
